xtask: Compress with gzip and rename to crate
For copr build, since we are using `%{crates_source}`, need to
update to compress with gzip and rename to crate.
Fixes build error:
```
error: Couldn't download https://crates.io/api/v1/crates/bootupd/0.2.31.14.g8361939/download#/bootupd-0.2.31.14.g8361939.crate
```