package: move to compare `version` instead of `timestamp`
Use `rpm::Evr` crate to parse and compare `version` when checking
for update.

Inspired by Timothee's pointer:
https://github.com/coreos/bootupd/pull/938#issuecomment-3118960479
Fixes: https://github.com/coreos/bootupd/issues/933

Additional info:
Use rpm `0.16.1` instead of `0.17` as 1.84 does not support
feature `edition2024` that is requried by 0.17:
```
error: failed to parse manifest at `/root/.cargo/registry/src/
index.crates.io-6f17d22bba15001f/rpm-0.17.0/Cargo.toml`

Caused by:
  feature `edition2024` is required

  The package requires the Cargo feature called `edition2024`,
but that feature is not stabilized in this version of Cargo
(1.84.1 (66221abde 2024-11-19)).
```